/* tslint:disable */
/* eslint-disable */
/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { HTTPValidationError } from '../models';
// @ts-ignore
import { InferenceRequest } from '../models';
// @ts-ignore
import { OutputTypeNullable } from '../models';
// @ts-ignore
import { PromptsNullable } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * ModelsApi - axios parameter creator
 * @export
 */
export const ModelsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Run Inference function of a model for segmenting and annotating human anatomies
         * @summary Run Inference
         * @param {InferenceRequest} inferenceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runInferenceVista3d: async (inferenceRequest: InferenceRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'inferenceRequest' is not null or undefined
            assertParamExists('runInferenceVista3d', 'inferenceRequest', inferenceRequest)
            const localVarPath = `/medicalimaging/nvidia/vista-3d`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: inferenceRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/medicalimaging/nvidia/vista-3d',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(inferenceRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ModelsApi - functional programming interface
 * @export
 */
export const ModelsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ModelsApiAxiosParamCreator(configuration)
    return {
        /**
         * Run Inference function of a model for segmenting and annotating human anatomies
         * @summary Run Inference
         * @param {ModelsApiRunInferenceVista3dRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runInferenceVista3d(requestParameters: ModelsApiRunInferenceVista3dRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Uint8Array | File | buffer.File>> {
            const inferenceRequest: InferenceRequest = {
                image: requestParameters.image,
                prompts: requestParameters.prompts,
                output: requestParameters.output
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.runInferenceVista3d(inferenceRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ModelsApi - factory interface
 * @export
 */
export const ModelsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ModelsApiFp(configuration)
    return {
        /**
         * Run Inference function of a model for segmenting and annotating human anatomies
         * @summary Run Inference
         * @param {ModelsApiRunInferenceVista3dRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runInferenceVista3d(requestParameters: ModelsApiRunInferenceVista3dRequest, options?: AxiosRequestConfig): AxiosPromise<Uint8Array | File | buffer.File> {
            return localVarFp.runInferenceVista3d(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for runInferenceVista3d operation in ModelsApi.
 * @export
 * @interface ModelsApiRunInferenceVista3dRequest
 */
export type ModelsApiRunInferenceVista3dRequest = {
    
} & InferenceRequest

/**
 * ModelsApiGenerated - object-oriented interface
 * @export
 * @class ModelsApiGenerated
 * @extends {BaseAPI}
 */
export class ModelsApiGenerated extends BaseAPI {
    /**
     * Run Inference function of a model for segmenting and annotating human anatomies
     * @summary Run Inference
     * @param {ModelsApiRunInferenceVista3dRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelsApiGenerated
     */
    public runInferenceVista3d(requestParameters: ModelsApiRunInferenceVista3dRequest, options?: AxiosRequestConfig) {
        return ModelsApiFp(this.configuration).runInferenceVista3d(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
