/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Brown Noise class containing perturbation parameters.  Parameters ---------- reddening : int = 2     Reddening in Fourier space. noise_amplitude : float = 0.05     Noise amplitude.
 * @export
 * @interface BrownNoise
 */
export interface BrownNoise {
    /**
     * 
     * @type {number}
     * @memberof BrownNoise
     */
    'noise_amplitude'?: number;
    /**
     * 
     * @type {number}
     * @memberof BrownNoise
     */
    'reddening'?: number;
    /**
     * 
     * @type {any}
     * @memberof BrownNoise
     */
    'type'?: any;
}

