/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Perturbation method to relatively adjust certain channels.  Parameters ---------- delta_surface_temperature: float     (signed) % of global average temperature to adjust t2m. delta_surface_wind_speed: float     (signed) % of temperature standard deviation to adjust u10m and v10m. delta_water_vapor: float     (signed) % of temperature standard deviation to adjust tcwv. delta_equator_pole_temperature_gradient: float     (signed) % of temperature standard deviation to adjust temperature gradient     for temperature at each geopotential height.
 * @export
 * @interface ChannelAdjust
 */
export interface ChannelAdjust {
    /**
     * 
     * @type {number}
     * @memberof ChannelAdjust
     */
    'delta_equator_pole_temperature_gradient'?: number;
    /**
     * 
     * @type {number}
     * @memberof ChannelAdjust
     */
    'delta_surface_temperature'?: number;
    /**
     * 
     * @type {number}
     * @memberof ChannelAdjust
     */
    'delta_surface_wind_speed'?: number;
    /**
     * 
     * @type {number}
     * @memberof ChannelAdjust
     */
    'delta_water_vapor'?: number;
    /**
     * 
     * @type {number}
     * @memberof ChannelAdjust
     */
    'noise_amplitude'?: number;
    /**
     * 
     * @type {any}
     * @memberof ChannelAdjust
     */
    'type'?: any;
}

