/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Choice } from './choice';
import { Usage } from './usage';

/**
 * 
 * @export
 * @interface ChatCompletion
 */
export interface ChatCompletion {
    /**
     * A unique identifier for the completion.
     * @type {string}
     * @memberof ChatCompletion
     */
    'id': string;
    /**
     * The list of completion choices the model generated for the input prompt.
     * @type {Array<Choice>}
     * @memberof ChatCompletion
     */
    'choices': Array<Choice>;
    /**
     * Usage statistics for the completion request.
     * @type {Usage}
     * @memberof ChatCompletion
     */
    'usage': Usage;
}

