/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ChoiceChunk } from './choice-chunk';

/**
 * 
 * @export
 * @interface ChatCompletionChunk
 */
export interface ChatCompletionChunk {
    /**
     * A unique identifier for the completion.
     * @type {string}
     * @memberof ChatCompletionChunk
     */
    'id': string;
    /**
     * The list of completion choices the model generated for the input prompt.
     * @type {Array<ChoiceChunk>}
     * @memberof ChatCompletionChunk
     */
    'choices': Array<ChoiceChunk>;
}

