/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ChatMessage } from './chat-message';

/**
 * 
 * @export
 * @interface ChatCompletionResponseChoice
 */
export interface ChatCompletionResponseChoice {
    /**
     * The index of the choice in the list of choices (always 0).
     * @type {number}
     * @memberof ChatCompletionResponseChoice
     */
    'index': number;
    /**
     * 
     * @type {ChatMessage}
     * @memberof ChatCompletionResponseChoice
     */
    'message': ChatMessage;
    /**
     * The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence, or `length` if the maximum number of tokens specified in the request was reached. Will be `null` if the model has not finished
     * @type {string}
     * @memberof ChatCompletionResponseChoice
     */
    'finish_reason'?: ChatCompletionResponseChoiceFinishReasonEnum;
}

type ChatCompletionResponseChoiceFinishReasonEnum = 'stop' | 'length'


