/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Message } from './message';

/**
 * 
 * @export
 * @interface ChoiceChunk
 */
export interface ChoiceChunk {
    /**
     * The index of the choice in the list of choices (always 0).
     * @type {number}
     * @memberof ChoiceChunk
     */
    'index'?: number;
    /**
     * A chat completion delta generated by streamed model responses.
     * @type {Message}
     * @memberof ChoiceChunk
     */
    'delta': Message;
    /**
     * The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence, or `length` if the maximum number of tokens specified in the request was reached. Will be `null` if the model has not finished generating.
     * @type {string}
     * @memberof ChoiceChunk
     */
    'finish_reason'?: ChoiceChunkFinishReasonEnum;
}

type ChoiceChunkFinishReasonEnum = 'stop' | 'length'


