/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Output } from './output';
import { SimulationParameters } from './simulation-parameters';

/**
 * 
 * @export
 * @interface Config
 */
export interface Config {
    /**
     * 
     * @type {SimulationParameters}
     * @memberof Config
     */
    'parameters': SimulationParameters;
    /**
     * 
     * @type {Array<Output>}
     * @memberof Config
     */
    'outputs'?: Array<Output>;
}

