/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UserImageContent } from './user-image-content';
import { UserTextContent } from './user-text-content';

/**
 * @type ContentPropertyAnyOfInner
 * @export
 */
export type ContentPropertyAnyOfInner = UserTextContent | UserImageContent;


