/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CreateEmbeddingRequestInput } from './create-embedding-request-input';

/**
 * 
 * @export
 * @interface CreateEmbeddingRequest
 */
export interface CreateEmbeddingRequest {
    /**
     * 
     * @type {CreateEmbeddingRequestInput}
     * @memberof CreateEmbeddingRequest
     */
    'input': CreateEmbeddingRequestInput;
    /**
     * ID of the embedding model.
     * @type {string}
     * @memberof CreateEmbeddingRequest
     */
    'model': string;
    /**
     * NV-Embed-QA and E5 models operate in `passage` or `query` mode, and thus require the `input_type` parameter. `passage` is used when generating embeddings during indexing. `query` is used when generating embeddings during querying. It is very important to use the correct `input_type`. Failure to do so will result in large drops in retrieval accuracy. As an alternative, it is possible to add the `-query` or `-passage` suffix to the `model` parameter like `NV-Embed-QA-query` and not use the `input_type` field at all for OpenAI API compliance. Please note that the GTE model _does not_ accept the `input_type` parameter since both the query and passage are processed in the same way.
     * @type {string}
     * @memberof CreateEmbeddingRequest
     */
    'input_type'?: CreateEmbeddingRequestInputTypeEnum;
    /**
     * The format to return the embeddings in.
     * @type {string}
     * @memberof CreateEmbeddingRequest
     */
    'encoding_format'?: CreateEmbeddingRequestEncodingFormatEnum;
    /**
     * Specifies how inputs longer than the maximum token length of the model are handled. Passing `START` discards the start of the input. `END` discards the end of the input. In both cases, input is discarded until the remaining input is exactly the maximum input token length for the model. If `NONE` is selected, when the input exceeds the maximum input token length an error will be returned.
     * @type {string}
     * @memberof CreateEmbeddingRequest
     */
    'truncate'?: CreateEmbeddingRequestTruncateEnum;
    /**
     * Not implemented, but provided for API compliance. This field is ignored.
     * @type {string}
     * @memberof CreateEmbeddingRequest
     */
    'user'?: string;
}

type CreateEmbeddingRequestInputTypeEnum = 'passage' | 'query'
type CreateEmbeddingRequestEncodingFormatEnum = 'float' | 'base64'
type CreateEmbeddingRequestTruncateEnum = 'NONE' | 'START' | 'END'


