/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CreateEmbeddingResponseUsage } from './create-embedding-response-usage';
import { EmbeddingObject } from './embedding-object';

/**
 * 
 * @export
 * @interface CreateEmbeddingResponse
 */
export interface CreateEmbeddingResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateEmbeddingResponse
     */
    'object'?: string;
    /**
     * 
     * @type {Array<EmbeddingObject>}
     * @memberof CreateEmbeddingResponse
     */
    'data'?: Array<EmbeddingObject>;
    /**
     * 
     * @type {string}
     * @memberof CreateEmbeddingResponse
     */
    'model'?: string;
    /**
     * 
     * @type {CreateEmbeddingResponseUsage}
     * @memberof CreateEmbeddingResponse
     */
    'usage'?: CreateEmbeddingResponseUsage;
}

