/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OptimizedRoutingDataProperty1 } from './optimized-routing-data-property1';

/**
 * 
 * @export
 * @interface CuOptApiManagedServiceEndpointRequest
 */
export interface CuOptApiManagedServiceEndpointRequest {
    /**
     * unused/ignored but retained for compatibility
     * @type {object}
     * @memberof CuOptApiManagedServiceEndpointRequest
     */
    'parameters'?: object | null;
    /**
     * Action to be performed by the service, validator action just validates input against format and base rules.
     * @type {string}
     * @memberof CuOptApiManagedServiceEndpointRequest
     */
    'action'?: CuOptApiManagedServiceEndpointRequestActionEnum;
    /**
     * 
     * @type {OptimizedRoutingDataProperty1}
     * @memberof CuOptApiManagedServiceEndpointRequest
     */
    'data': OptimizedRoutingDataProperty1 | null;
    /**
     * cuOpt client version. Set to \'custom\' to skip version check.
     * @type {string}
     * @memberof CuOptApiManagedServiceEndpointRequest
     */
    'client_version'?: string | null;
}

type CuOptApiManagedServiceEndpointRequestActionEnum = 'cuOpt_OptimizedRouting' | 'cuOpt_RoutingValidator' | '0'


