/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Diagnostic and Statistic Options.
 * @export
 * @enum {string}
 */
export type DiagnosticTypes = 'full_ensemble' | 'control' | 'histogram' | 'ensemble_stats' | 'kde' | 'ensemble_svd' | 'climatenet'

