/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DiagnosticTypes } from './diagnostic-types';

/**
 * Diagnostic class defining the diagnostic, any functions applied to the diagnostic, the channels of interest, and any diagnostic properties.  Parameters ----------- function : List[str]     Any functions applied to the diagnostic during     post-processing. channels : List[str]     Channels to save diagnostics for, must be a subset     of the model channel list. properties : dict     Diagnostic-specific properties.
 * @export
 * @interface Diagnostic
 */
export interface Diagnostic {
    /**
     * 
     * @type {Array<string>}
     * @memberof Diagnostic
     */
    'channels'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Diagnostic
     */
    'function'?: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof Diagnostic
     */
    'properties'?: object;
    /**
     * Diagnostic and Statistic Options.
     * @type {DiagnosticTypes}
     * @memberof Diagnostic
     */
    'type': DiagnosticTypes;
}

