/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmbeddingObjectEmbedding } from './embedding-object-embedding';

/**
 * 
 * @export
 * @interface EmbeddingObject
 */
export interface EmbeddingObject {
    /**
     * 
     * @type {string}
     * @memberof EmbeddingObject
     */
    'object': string;
    /**
     * 
     * @type {EmbeddingObjectEmbedding}
     * @memberof EmbeddingObject
     */
    'embedding': EmbeddingObjectEmbedding;
    /**
     * The index of the embedding in the list of embeddings.
     * @type {number}
     * @memberof EmbeddingObject
     */
    'index': number;
}

