/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Entity
 */
export interface Entity {
    /**
     * Term used to refer to the specific phrase mentioned in the text.
     * @type {string}
     * @memberof Entity
     */
    'phrase': string;
    /**
     * Tuple of start and end indices that indicate the position of the entity term within the text.  <br>These indices help identify the specific location of the entity term within the text.  <br>The indices mentioned are zero-based, which means they start counting from zero. The both indices are inclusive, <br>meaning it is included in the range.
     * @type {Array}
     * @memberof Entity
     */
    'substring': Array;
    /**
     * Bounding boxes are rectangle-shaped boxes that surround objects or areas of interest in an image.  <br>They are used to identify and describe the entities in the image. These are defined using four values:  <br>top left x, top left y, bottom right x, and bottom right y. The top left x and top left y values indicate  <br>the normalized coordinates of the upper-left corner of the bounding box, while the bottom right x and bottom right y values  <br>represent the normalized coordinates of the lower-right corner of the bounding box. 
     * @type {Array<Array>}
     * @memberof Entity
     */
    'bboxes': Array<Array>;
}

