/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FeasibleResultData2 } from './feasible-result-data2';
import { VehicleData4 } from './vehicle-data4';

/**
 * Feasible solution
 * @export
 * @interface FeasibleSolve1SolverResponse
 */
export interface FeasibleSolve1SolverResponse {
    /**
     * 0 - Solution is available  1 - Infeasible solution is available  
     * @type {number}
     * @memberof FeasibleSolve1SolverResponse
     */
    'status'?: number;
    /**
     * Number of vehicle being used for the solution
     * @type {number}
     * @memberof FeasibleSolve1SolverResponse
     */
    'num_vehicles'?: number;
    /**
     * Total cost of the solution
     * @type {number}
     * @memberof FeasibleSolve1SolverResponse
     */
    'solution_cost'?: number;
    /**
     * All the details of vehicle routes and timestamps
     * @type {{ [key: string]: VehicleData4; }}
     * @memberof FeasibleSolve1SolverResponse
     */
    'vehicle_data'?: { [key: string]: VehicleData4; };
    /**
     * Any information pertaining to the run.
     * @type {string}
     * @memberof FeasibleSolve1SolverResponse
     */
    'msg'?: string | null;
}

