/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FeasibleSolve1SolverResponse } from './feasible-solve1-solver-response';

/**
 * 
 * @export
 * @interface FeasibleSolve1
 */
export interface FeasibleSolve1 {
    /**
     * 
     * @type {FeasibleSolve1SolverResponse}
     * @memberof FeasibleSolve1
     */
    'solver_response'?: FeasibleSolve1SolverResponse;
    /**
     * Etl and Solve times of the solve call
     * @type {object}
     * @memberof FeasibleSolve1
     */
    'perf_times'?: object | null;
}

