/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Fq2bamRequestBody
 */
export interface Fq2bamRequestBody {
    /**
     * 
     * @type {string}
     * @memberof Fq2bamRequestBody
     */
    'in_ref_tarball': string;
    /**
     * 
     * @type {string}
     * @memberof Fq2bamRequestBody
     */
    'in_fq': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Fq2bamRequestBody
     */
    'out_bam': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Fq2bamRequestBody
     */
    'out_bam_parts_manifest': string;
    /**
     * 
     * @type {string}
     * @memberof Fq2bamRequestBody
     */
    'out_bai': string;
    /**
     * 
     * @type {string}
     * @memberof Fq2bamRequestBody
     */
    'out_chrs': string;
    /**
     * 
     * @type {string}
     * @memberof Fq2bamRequestBody
     */
    'out_stderr': string;
    /**
     * 
     * @type {string}
     * @memberof Fq2bamRequestBody
     */
    'out_stdout': string;
    /**
     * 
     * @type {string}
     * @memberof Fq2bamRequestBody
     */
    'additional_args'?: string;
}

