/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TextPrompt } from './text-prompt';

/**
 * 
 * @export
 * @interface ImageRequest
 */
export interface ImageRequest {
    /**
     * Height of the image to generate, in pixels. Only height=1024 is supported
     * @type {number}
     * @memberof ImageRequest
     */
    'height'?: number | null;
    /**
     * Width of the image to generate, in pixels. Only width=1024 is supported
     * @type {number}
     * @memberof ImageRequest
     */
    'width'?: number | null;
    /**
     * An array of text prompts to use for generation
     * @type {Array<TextPrompt>}
     * @memberof ImageRequest
     */
    'text_prompts': Array<TextPrompt>;
    /**
     * How strictly the diffusion process adheres to the prompt text (higher values keep your image closer to your prompt).
     * @type {number}
     * @memberof ImageRequest
     */
    'cfg_scale'?: number | null;
    /**
     * clip guidance preset. Only clip_guidance_preset=`NONE` is supported
     * @type {any}
     * @memberof ImageRequest
     */
    'clip_guidance_preset'?: any | null;
    /**
     * The sampler to use for generation. Varying diffusion samplers will vary outputs significantly.
     * @type {string}
     * @memberof ImageRequest
     */
    'sampler'?: ImageRequestSamplerEnum;
    /**
     * Number of images to generate. Only samples=1 is supported
     * @type {number}
     * @memberof ImageRequest
     */
    'samples'?: number | null;
    /**
     * The seed which governs generation. Omit this option or use 0 for a random seed
     * @type {number}
     * @memberof ImageRequest
     */
    'seed'?: number | null;
    /**
     * Number of diffusion steps to run
     * @type {number}
     * @memberof ImageRequest
     */
    'steps'?: number | null;
    /**
     * Pass in a style preset to guide the image model towards a particular style. This list of style presets is subject to change. style_preset=`none` is supported
     * @type {any}
     * @memberof ImageRequest
     */
    'style_preset'?: any | null;
}

type ImageRequestSamplerEnum = 'DDIM' | 'K_EULER_ANCESTRAL' | 'K_LMS' | 'K_DPM_2_ANCESTRAL'


