/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InFeasibleSolve1SolverInfeasibleResponse } from './in-feasible-solve1-solver-infeasible-response';

/**
 * 
 * @export
 * @interface InFeasibleSolve1
 */
export interface InFeasibleSolve1 {
    /**
     * 
     * @type {InFeasibleSolve1SolverInfeasibleResponse}
     * @memberof InFeasibleSolve1
     */
    'solver_infeasible_response'?: InFeasibleSolve1SolverInfeasibleResponse;
    /**
     * Etl and Solve times of the solve call
     * @type {object}
     * @memberof InFeasibleSolve1
     */
    'perf_times'?: object | null;
}

