/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OutputTypeNullable } from './output-type-nullable';
import { PromptsNullable } from './prompts-nullable';

/**
 * 
 * @export
 * @interface InferenceRequest
 */
export interface InferenceRequest {
    /**
     * A Valid URL representing a 3D medical Image (nifti/nrrd)
     * @type {string}
     * @memberof InferenceRequest
     */
    'image': string;
    /**
     * 
     * @type {PromptsNullable}
     * @memberof InferenceRequest
     */
    'prompts'?: PromptsNullable | null;
    /**
     * 
     * @type {OutputTypeNullable}
     * @memberof InferenceRequest
     */
    'output'?: OutputTypeNullable | null;
}

