/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Inference Model Options.
 * @export
 * @enum {string}
 */
export type InferenceModels = 'persistence_1step' | 'sfno_73ch'

