/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ContentProperty1 } from './content-property1';
import { Entity } from './entity';

/**
 * 
 * @export
 * @interface MessageWithEntities
 */
export interface MessageWithEntities {
    /**
     * The role of the message author.
     * @type {string}
     * @memberof MessageWithEntities
     */
    'role': MessageWithEntitiesRoleEnum;
    /**
     * 
     * @type {ContentProperty1}
     * @memberof MessageWithEntities
     */
    'content'?: ContentProperty1 | null;
    /**
     * List of entities along with bounding boxes referring the generated text and input image
     * @type {Array<Entity>}
     * @memberof MessageWithEntities
     */
    'entities': Array<Entity>;
}

type MessageWithEntitiesRoleEnum = 'user' | 'assistant'


