/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ContentProperty1 } from './content-property1';
import { Entity } from './entity';
import { Message } from './message';
import { MessageWithEntities } from './message-with-entities';

/**
 * @type MessagesProperty1Inner
 * @export
 */
export type MessagesProperty1Inner = Message | MessageWithEntities;


