/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ContentProperty } from './content-property';

/**
 * 
 * @export
 * @interface Message
 */
export interface Message {
    /**
     * The role of the message author.
     * @type {string}
     * @memberof Message
     */
    'role': MessageRoleEnum;
    /**
     * 
     * @type {ContentProperty}
     * @memberof Message
     */
    'content'?: ContentProperty | null;
    /**
     * The name of the author of this message. Cannot be used with role=`system`. May contain a-z, A-Z, 0-9, and underscores, with a maximum length of 64 characters.
     * @type {string}
     * @memberof Message
     */
    'name'?: string | null;
}

type MessageRoleEnum = 'system' | 'user' | 'assistant'


