/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ModelInfo
 */
export interface ModelInfo {
    /**
     * Description of Model
     * @type {string}
     * @memberof ModelInfo
     */
    'description': string;
    /**
     * Version of Pre-trained Model
     * @type {string}
     * @memberof ModelInfo
     */
    'version': string;
    /**
     * Name of Model
     * @type {string}
     * @memberof ModelInfo
     */
    'name': string;
    /**
     * Label Names/Indices supported by the Model
     * @type {{ [key: string]: string; }}
     * @memberof ModelInfo
     */
    'labels': { [key: string]: string; };
}

