/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ControlGenerationAlgo } from './control-generation-algo';
import { ControlGenerationProp } from './control-generation-prop';

/**
 * 
 * @export
 * @interface MoleculeGenerationBody
 */
export interface MoleculeGenerationBody {
    /**
     * 
     * @type {ControlGenerationAlgo}
     * @memberof MoleculeGenerationBody
     */
    'algorithm'?: ControlGenerationAlgo;
    /**
     * 
     * @type {string}
     * @memberof MoleculeGenerationBody
     */
    'smi'?: string;
    /**
     * 
     * @type {number}
     * @memberof MoleculeGenerationBody
     */
    'num_molecules'?: number;
    /**
     * 
     * @type {number}
     * @memberof MoleculeGenerationBody
     */
    'iterations'?: number;
    /**
     * 
     * @type {ControlGenerationProp}
     * @memberof MoleculeGenerationBody
     */
    'property_name'?: ControlGenerationProp;
    /**
     * 
     * @type {number}
     * @memberof MoleculeGenerationBody
     */
    'particles'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof MoleculeGenerationBody
     */
    'minimize'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof MoleculeGenerationBody
     */
    'min_similarity'?: number;
    /**
     * 
     * @type {number}
     * @memberof MoleculeGenerationBody
     */
    'scaled_radius'?: number;
}

