/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmbeddingFormatNullable } from './embedding-format-nullable';

/**
 * 
 * @export
 * @interface MolecularDecodeRequest
 */
export interface MolecularDecodeRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof MolecularDecodeRequest
     */
    'shape': Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof MolecularDecodeRequest
     */
    'embeddings': Array<number> | null;
    /**
     * 
     * @type {string}
     * @memberof MolecularDecodeRequest
     */
    'asset_id'?: string | null;
    /**
     * Input format
     * @type {EmbeddingFormatNullable}
     * @memberof MolecularDecodeRequest
     */
    'format'?: EmbeddingFormatNullable | null;
}

