/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LigandFormat } from './ligand-format';

/**
 * 
 * @export
 * @interface MolecularDockingRequest
 */
export interface MolecularDockingRequest {
    /**
     * Ligand to be docked. Mol2 string or NVCF asset id
     * @type {string}
     * @memberof MolecularDockingRequest
     */
    'ligand': string;
    /**
     * Ligand(mol2) to be docked. Mol2 string or NVCF asset id
     * @type {LigandFormat}
     * @memberof MolecularDockingRequest
     */
    'ligand_file_type': LigandFormat;
    /**
     * Protein(PDB). PDB string or NVCF asset id
     * @type {string}
     * @memberof MolecularDockingRequest
     */
    'protein': string;
    /**
     * Number of poses to generate
     * @type {number}
     * @memberof MolecularDockingRequest
     */
    'num_poses'?: number;
    /**
     * Number of diffusion time divisions
     * @type {number}
     * @memberof MolecularDockingRequest
     */
    'time_divisions'?: number;
    /**
     * Number of diffusion steps to be computed
     * @type {number}
     * @memberof MolecularDockingRequest
     */
    'steps'?: number;
    /**
     * Return the trajectory
     * @type {boolean}
     * @memberof MolecularDockingRequest
     */
    'save_trajectory'?: boolean;
    /**
     * Are the files for ligand and protein staged?
     * @type {boolean}
     * @memberof MolecularDockingRequest
     */
    'is_staged'?: boolean;
}

