/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmbeddingFormat } from './embedding-format';

/**
 * 
 * @export
 * @interface MolecularEmbeddingRequest
 */
export interface MolecularEmbeddingRequest {
    /**
     * SMILES
     * @type {Array<string>}
     * @memberof MolecularEmbeddingRequest
     */
    'smis': Array<string>;
    /**
     * Expected embedding output format
     * @type {EmbeddingFormat}
     * @memberof MolecularEmbeddingRequest
     */
    'format'?: EmbeddingFormat;
}

