/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A type signifier for multimodal data.  Supported data types: text.
 * @export
 * @interface MultiModalData
 */
export interface MultiModalData {
    /**
     * 
     * @type {string}
     * @memberof MultiModalData
     */
    'text': string;
}

