/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Values provided dictate the linear combination of factors used to evaluate solution quality.Only prize will be negated, all others gets accumulated. That\'s why sometime you might come across negative value as solution cost.
 * @export
 * @interface ObjectiveProperty
 */
export interface ObjectiveProperty {
    /**
     * dtype: float32.     The weight assigned to minimizing the cost for a given solution, default value is 1
     * @type {number}
     * @memberof ObjectiveProperty
     */
    'cost'?: number | null;
    /**
     * dtype: float32.    The weight assigned to minimizing total travel time for a given solution (includes drive, service and wait time)
     * @type {number}
     * @memberof ObjectiveProperty
     */
    'travel_time'?: number | null;
    /**
     * dtype: float32.    The weight assigned to the variance in the number of orders served by each route.
     * @type {number}
     * @memberof ObjectiveProperty
     */
    'variance_route_size'?: number | null;
    /**
     * dtype: float32.    The weight assigned to the variance in the accumulated service times of each route
     * @type {number}
     * @memberof ObjectiveProperty
     */
    'variance_route_service_time'?: number | null;
    /**
     * dtype: float32.    The weight assigned to the prize in accumulated prizes for each job fulfilled.This will be negated from overall values accumulated with other objectives.For example, if cost accumulated is 10 and objective value for it is 1, and if the prize accumulated is 3 and objective is 2, then total cost would look something like this 10 x 1 - 3 x 2 = 4.
     * @type {number}
     * @memberof ObjectiveProperty
     */
    'prize'?: number | null;
    /**
     * dtype: float32.    The weight assigned to the accumulated fixed costs of each vehicle used in solution
     * @type {number}
     * @memberof ObjectiveProperty
     */
    'vehicle_fixed_cost'?: number | null;
}

