/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OptimizedRoutingDataFleetData } from './optimized-routing-data-fleet-data';
import { OptimizedRoutingDataTaskData } from './optimized-routing-data-task-data';
import { UpdateCostMatricesProperty } from './update-cost-matrices-property';
import { UpdateCostMatricesProperty1 } from './update-cost-matrices-property1';
import { UpdateSolverSettingsConfigProperty } from './update-solver-settings-config-property';
import { UpdateWaypointGraphDataProperty } from './update-waypoint-graph-data-property';
import { UpdateWaypointGraphDataProperty1 } from './update-waypoint-graph-data-property1';

/**
 * 
 * @export
 * @interface OptimizedRoutingData
 */
export interface OptimizedRoutingData {
    /**
     * 
     * @type {UpdateWaypointGraphDataProperty}
     * @memberof OptimizedRoutingData
     */
    'cost_waypoint_graph_data'?: UpdateWaypointGraphDataProperty | null;
    /**
     * 
     * @type {UpdateWaypointGraphDataProperty1}
     * @memberof OptimizedRoutingData
     */
    'travel_time_waypoint_graph_data'?: UpdateWaypointGraphDataProperty1 | null;
    /**
     * 
     * @type {UpdateCostMatricesProperty}
     * @memberof OptimizedRoutingData
     */
    'cost_matrix_data'?: UpdateCostMatricesProperty | null;
    /**
     * 
     * @type {UpdateCostMatricesProperty1}
     * @memberof OptimizedRoutingData
     */
    'travel_time_matrix_data'?: UpdateCostMatricesProperty1 | null;
    /**
     * 
     * @type {OptimizedRoutingDataFleetData}
     * @memberof OptimizedRoutingData
     */
    'fleet_data': OptimizedRoutingDataFleetData;
    /**
     * 
     * @type {OptimizedRoutingDataTaskData}
     * @memberof OptimizedRoutingData
     */
    'task_data': OptimizedRoutingDataTaskData;
    /**
     * 
     * @type {UpdateSolverSettingsConfigProperty}
     * @memberof OptimizedRoutingData
     */
    'solver_config'?: UpdateSolverSettingsConfigProperty | null;
}

