/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OptimizedRoutingDataPropertyFleetData } from './optimized-routing-data-property-fleet-data';
import { OptimizedRoutingDataPropertyTaskData } from './optimized-routing-data-property-task-data';
import { UpdateCostMatricesProperty2 } from './update-cost-matrices-property2';
import { UpdateCostMatricesProperty3 } from './update-cost-matrices-property3';
import { UpdateSolverSettingsConfigProperty1 } from './update-solver-settings-config-property1';
import { UpdateWaypointGraphDataProperty2 } from './update-waypoint-graph-data-property2';
import { UpdateWaypointGraphDataProperty3 } from './update-waypoint-graph-data-property3';

/**
 * The data that needs to be processed by the service. For detailed explanations of each field, please consult the following link: <a href=\"https://docs.nvidia.com/cuopt/service/latest/data-requirements.html\">data requirements</a> . To ensure best practices, please refer to: <a href=\"https://docs.nvidia.com/cuopt/service/latest/best-practices.html\">best practices</a>. For examples, you can find them at: <a href=\"https://github.com/NVIDIA/cuOpt-Resources/tree/branch-23.10/notebooks/routing/service\">notebooks</a>. If the size of the data exceeds 250KB, please utilize the large assets API to upload it to s3. In such cases, set the data as null and include the header NVCF-INPUT-ASSET-REFERENCES: $ASSET_ID in the POST request.
 * @export
 * @interface OptimizedRoutingDataProperty
 */
export interface OptimizedRoutingDataProperty {
    /**
     * 
     * @type {UpdateWaypointGraphDataProperty2}
     * @memberof OptimizedRoutingDataProperty
     */
    'cost_waypoint_graph_data'?: UpdateWaypointGraphDataProperty2 | null;
    /**
     * 
     * @type {UpdateWaypointGraphDataProperty3}
     * @memberof OptimizedRoutingDataProperty
     */
    'travel_time_waypoint_graph_data'?: UpdateWaypointGraphDataProperty3 | null;
    /**
     * 
     * @type {UpdateCostMatricesProperty2}
     * @memberof OptimizedRoutingDataProperty
     */
    'cost_matrix_data'?: UpdateCostMatricesProperty2 | null;
    /**
     * 
     * @type {UpdateCostMatricesProperty3}
     * @memberof OptimizedRoutingDataProperty
     */
    'travel_time_matrix_data'?: UpdateCostMatricesProperty3 | null;
    /**
     * 
     * @type {OptimizedRoutingDataPropertyFleetData}
     * @memberof OptimizedRoutingDataProperty
     */
    'fleet_data': OptimizedRoutingDataPropertyFleetData;
    /**
     * 
     * @type {OptimizedRoutingDataPropertyTaskData}
     * @memberof OptimizedRoutingDataProperty
     */
    'task_data': OptimizedRoutingDataPropertyTaskData;
    /**
     * 
     * @type {UpdateSolverSettingsConfigProperty1}
     * @memberof OptimizedRoutingDataProperty
     */
    'solver_config'?: UpdateSolverSettingsConfigProperty1 | null;
}

