/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Provide any ITK output type for segmentation masks
 * @export
 * @interface OutputTypeNullable
 */
export interface OutputTypeNullable {
    /**
     * Supported ITK Extension for segmentation mask
     * @type {string}
     * @memberof OutputTypeNullable
     */
    'extension': string;
    /**
     * Output Data Type for segmentation mask
     * @type {string}
     * @memberof OutputTypeNullable
     */
    'dtype': string;
}

