/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Diagnostic } from './diagnostic';
import { DomainProperty } from './domain-property';

/**
 * Base model to construct a domain.  Parameters ---------- domain : Union[Window, Region, MultiPoint]     Information about region geometry diagnostics : List[Diagnostics]     List of diagnostics.
 * @export
 * @interface Output
 */
export interface Output {
    /**
     * 
     * @type {Array<Diagnostic>}
     * @memberof Output
     */
    'diagnostics'?: Array<Diagnostic>;
    /**
     * 
     * @type {DomainProperty}
     * @memberof Output
     */
    'domain': DomainProperty;
}

