/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BredVector } from './bred-vector';
import { BrownNoise } from './brown-noise';
import { ChannelAdjust } from './channel-adjust';
import { NoPerturb } from './no-perturb';
import { SphericalGaussian } from './spherical-gaussian';

/**
 * @type PerturbationMethodProperty
 * @export
 */
export type PerturbationMethodProperty = NoPerturb | BrownNoise | BredVector | SphericalGaussian | ChannelAdjust;


