/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LabelNamesIndicesPropertyInner } from './label-names-indices-property-inner';

/**
 * User prompts for running Interactive Annotation
 * @export
 * @interface PromptsNullable
 */
export interface PromptsNullable {
    /**
     * Label Names/Indices as class prompts
     * @type {Array<LabelNamesIndicesPropertyInner>}
     * @memberof PromptsNullable
     */
    'classes'?: Array<LabelNamesIndicesPropertyInner> | null;
    /**
     * User Click Points as prompts
     * @type {{ [key: string]: Array<Array>; }}
     * @memberof PromptsNullable
     */
    'points'?: { [key: string]: Array<Array>; } | null;
}

