/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ResponseModel1
 */
export interface ResponseModel1 {
    /**
     * Response
     * @type {object}
     * @memberof ResponseModel1
     */
    'response': object;
    /**
     * List of warnings for users to handle issues
     * @type {Array<string>}
     * @memberof ResponseModel1
     */
    'warnings'?: Array<string>;
    /**
     * Any notes for users
     * @type {Array<string>}
     * @memberof ResponseModel1
     */
    'notes'?: Array<string>;
}

