/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FeasibleSolve1 } from './feasible-solve1';
import { FeasibleSolve1SolverResponse } from './feasible-solve1-solver-response';
import { InFeasibleSolve1 } from './in-feasible-solve1';
import { InFeasibleSolve1SolverInfeasibleResponse } from './in-feasible-solve1-solver-infeasible-response';

/**
 * @type ResponseProperty
 * Response
 * @export
 */
export type ResponseProperty = FeasibleSolve1 | InFeasibleSolve1;


