/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ResponseProperty } from './response-property';

/**
 * 
 * @export
 * @interface ResponseModel
 */
export interface ResponseModel {
    /**
     * 
     * @type {ResponseProperty}
     * @memberof ResponseModel
     */
    'response': ResponseProperty;
    /**
     * List of warnings for users to handle issues
     * @type {Array<string>}
     * @memberof ResponseModel
     */
    'warnings'?: Array<string>;
    /**
     * Any notes for users
     * @type {Array<string>}
     * @memberof ResponseModel
     */
    'notes'?: Array<string>;
}

