/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * @type ServiceTimesProperty
 * dtype: int32, time >= 0.    Service time for each task. Accepts a list of service times for all vehicles. In case of vehicle specific service times, accepts a dict with key as vehicle id and value as list of service times.Example schema: In case all vehicles have same service times,         [tsk_1_srv_time, tsk_2_srv_time, tsk_3_srv_time]        In case, there are 2 types of vehicle types and each of them have different service times,        {            type-1: [tsk_1_srv_time, tsk_3_srv_time, tsk_3_srv_time],            type-2: [tsk_1_srv_time, tsk_3_srv_time, tsk_3_srv_time]        }
 * @export
 */
export type ServiceTimesProperty = Array<number> | any;


