/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * @type StopProperty
 * A string or a list of strings where the API will stop generating further tokens. The returned text will not contain the stop sequence.
 * @export
 */
export type StopProperty = Array<string> | string;


