/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TextPrompt
 */
export interface TextPrompt {
    /**
     * The prompt itself
     * @type {string}
     * @memberof TextPrompt
     */
    'text': string;
    /**
     * Weight of the prompt, only weight=1.0 for prompt and weight=-1 for negative prompt is supported
     * @type {number}
     * @memberof TextPrompt
     */
    'weight'?: TextPromptWeightEnum;
}

type TextPromptWeightEnum = 1 | -1


