/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UniversalVariantCallingBody
 */
export interface UniversalVariantCallingBody {
    /**
     * A URL to a flat tarfile containing the reference genome and indices.
     * @type {string}
     * @memberof UniversalVariantCallingBody
     */
    'in_ref_tarball': string;
    /**
     * A URL to a BAM file.
     * @type {string}
     * @memberof UniversalVariantCallingBody
     */
    'in_bam': string;
    /**
     * A URL to the BAM index.
     * @type {string}
     * @memberof UniversalVariantCallingBody
     */
    'in_bai': string;
    /**
     * The sequencing read mode to use [shortread].
     * @type {string}
     * @memberof UniversalVariantCallingBody
     */
    'mode'?: string;
    /**
     * Output genomic VCF, rather than VCF.
     * @type {boolean}
     * @memberof UniversalVariantCallingBody
     */
    'use_gvcf'?: boolean;
    /**
     * Use the Whole Exome Model
     * @type {boolean}
     * @memberof UniversalVariantCallingBody
     */
    'use_wes_model'?: boolean;
    /**
     * A list of presigned S3 URLs for file upload.
     * @type {Array<string>}
     * @memberof UniversalVariantCallingBody
     */
    'out_variants': Array<string>;
    /**
     * A single S3 presigned POST URL for the multipart signing manifest of out_variants.
     * @type {string}
     * @memberof UniversalVariantCallingBody
     */
    'out_variants_parts_manifest': string;
    /**
     * A presigned POST URL.
     * @type {string}
     * @memberof UniversalVariantCallingBody
     */
    'out_stderr': string;
    /**
     * A presigned POST URL.
     * @type {string}
     * @memberof UniversalVariantCallingBody
     */
    'out_stdout': string;
    /**
     * 
     * @type {string}
     * @memberof UniversalVariantCallingBody
     */
    'additional_args'?: string;
}

