/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WaypointGraph1 } from './waypoint-graph1';

/**
 * Waypoint graph with weights as cost to travel from A to B  and B to A. If there are different types of vehicles  they can be provided with key value pair  where key is vehicle-type and value is the graph. Value of  vehicle type should be within [0, 255]
 * @export
 * @interface UpdateWaypointGraphDataProperty4
 */
export interface UpdateWaypointGraphDataProperty4 {
    /**
     * 
     * @type {{ [key: string]: WaypointGraph1; }}
     * @memberof UpdateWaypointGraphDataProperty4
     */
    'waypoint_graph'?: { [key: string]: WaypointGraph1; } | null;
}

