/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ObjectiveProperty2 } from './objective-property2';

/**
 * 
 * @export
 * @interface UpdateSolverSettingsConfigProperty1
 */
export interface UpdateSolverSettingsConfigProperty1 {
    /**
     * SolverSettings time limit
     * @type {number}
     * @memberof UpdateSolverSettingsConfigProperty1
     */
    'time_limit'?: number | null;
    /**
     * 
     * @type {ObjectiveProperty2}
     * @memberof UpdateSolverSettingsConfigProperty1
     */
    'objectives'?: ObjectiveProperty2 | null;
    /**
     * Dump configuration information in a given file as yaml
     * @type {string}
     * @memberof UpdateSolverSettingsConfigProperty1
     */
    'config_file'?: string | null;
    /**
     * Displaying internal information during the solver execution.
     * @type {boolean}
     * @memberof UpdateSolverSettingsConfigProperty1
     */
    'verbose_mode'?: boolean | null;
    /**
     * Displaying constraint error information during the solver execution.
     * @type {boolean}
     * @memberof UpdateSolverSettingsConfigProperty1
     */
    'error_logging'?: boolean | null;
    /**
     * Note: Prize collection is recommend for finer control over     what tasks would be picked or dropped. Drops infeasible tasks and returns routes for only feasible tasks. This should be used when solver fails to find a solution to fulfill all the tasks/order, 
     * @type {boolean}
     * @memberof UpdateSolverSettingsConfigProperty1
     */
    'drop_infeasible_tasks'?: boolean | null;
}

