/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WaypointGraph } from './waypoint-graph';

/**
 * 
 * @export
 * @interface UpdateWaypointGraphData
 */
export interface UpdateWaypointGraphData {
    /**
     * 
     * @type {{ [key: string]: WaypointGraph; }}
     * @memberof UpdateWaypointGraphData
     */
    'waypoint_graph'?: { [key: string]: WaypointGraph; } | null;
}

