/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ObjectiveProperty1 } from './objective-property1';

/**
 * 
 * @export
 * @interface UpdateSolverSettingsConfig
 */
export interface UpdateSolverSettingsConfig {
    /**
     * SolverSettings time limit
     * @type {number}
     * @memberof UpdateSolverSettingsConfig
     */
    'time_limit'?: number | null;
    /**
     * 
     * @type {ObjectiveProperty1}
     * @memberof UpdateSolverSettingsConfig
     */
    'objectives'?: ObjectiveProperty1 | null;
    /**
     * Dump configuration information in a given file as yaml
     * @type {string}
     * @memberof UpdateSolverSettingsConfig
     */
    'config_file'?: string | null;
    /**
     * Displaying internal information during the solver execution.
     * @type {boolean}
     * @memberof UpdateSolverSettingsConfig
     */
    'verbose_mode'?: boolean | null;
    /**
     * Displaying constraint error information during the solver execution.
     * @type {boolean}
     * @memberof UpdateSolverSettingsConfig
     */
    'error_logging'?: boolean | null;
    /**
     * Note: Prize collection is recommend for finer control over     what tasks would be picked or dropped. Drops infeasible tasks and returns routes for only feasible tasks. This should be used when solver fails to find a solution to fulfill all the tasks/order, 
     * @type {boolean}
     * @memberof UpdateSolverSettingsConfig
     */
    'drop_infeasible_tasks'?: boolean | null;
}

