/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ObjectiveProperty3 } from './objective-property3';

/**
 * 
 * @export
 * @interface UpdateSolverSettingsConfigProperty2
 */
export interface UpdateSolverSettingsConfigProperty2 {
    /**
     * SolverSettings time limit
     * @type {number}
     * @memberof UpdateSolverSettingsConfigProperty2
     */
    'time_limit'?: number | null;
    /**
     * 
     * @type {ObjectiveProperty3}
     * @memberof UpdateSolverSettingsConfigProperty2
     */
    'objectives'?: ObjectiveProperty3 | null;
    /**
     * Dump configuration information in a given file as yaml
     * @type {string}
     * @memberof UpdateSolverSettingsConfigProperty2
     */
    'config_file'?: string | null;
    /**
     * Displaying internal information during the solver execution.
     * @type {boolean}
     * @memberof UpdateSolverSettingsConfigProperty2
     */
    'verbose_mode'?: boolean | null;
    /**
     * Displaying constraint error information during the solver execution.
     * @type {boolean}
     * @memberof UpdateSolverSettingsConfigProperty2
     */
    'error_logging'?: boolean | null;
    /**
     * Note: Prize collection is recommend for finer control over     what tasks would be picked or dropped. Drops infeasible tasks and returns routes for only feasible tasks. This should be used when solver fails to find a solution to fulfill all the tasks/order, 
     * @type {boolean}
     * @memberof UpdateSolverSettingsConfigProperty2
     */
    'drop_infeasible_tasks'?: boolean | null;
}

