/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ObjectiveProperty } from './objective-property';

/**
 * 
 * @export
 * @interface UpdateSolverSettingsConfigProperty
 */
export interface UpdateSolverSettingsConfigProperty {
    /**
     * SolverSettings time limit
     * @type {number}
     * @memberof UpdateSolverSettingsConfigProperty
     */
    'time_limit'?: number | null;
    /**
     * 
     * @type {ObjectiveProperty}
     * @memberof UpdateSolverSettingsConfigProperty
     */
    'objectives'?: ObjectiveProperty | null;
    /**
     * Dump configuration information in a given file as yaml
     * @type {string}
     * @memberof UpdateSolverSettingsConfigProperty
     */
    'config_file'?: string | null;
    /**
     * Displaying internal information during the solver execution.
     * @type {boolean}
     * @memberof UpdateSolverSettingsConfigProperty
     */
    'verbose_mode'?: boolean | null;
    /**
     * Displaying constraint error information during the solver execution.
     * @type {boolean}
     * @memberof UpdateSolverSettingsConfigProperty
     */
    'error_logging'?: boolean | null;
    /**
     * Note: Prize collection is recommend for finer control over     what tasks would be picked or dropped. Drops infeasible tasks and returns routes for only feasible tasks. This should be used when solver fails to find a solution to fulfill all the tasks/order, 
     * @type {boolean}
     * @memberof UpdateSolverSettingsConfigProperty
     */
    'drop_infeasible_tasks'?: boolean | null;
}

