/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Sqaure matrix with time to travel from A to B and B to A.  If there are different types of vehicles which have different  travel time matrices, they can be provided with key value pair  where key is vehicle-type and value is time matrix. Value of  vehicle type should be within [0, 255]
 * @export
 * @interface UpdateCostMatricesProperty5
 */
export interface UpdateCostMatricesProperty5 {
    /**
     * dtype : vehicle-type (uint8), cost (float32), cost >= 0.     Sqaure matrix with cost to travel from A to B and B to A.  If there different types of vehicles which have different  cost matrices, they can be provided with key value pair  where key is vehicle-type and value is cost matrix. Value of  vehicle type should be within [0, 255]
     * @type {{ [key: string]: Array<Array<number>>; }}
     * @memberof UpdateCostMatricesProperty5
     */
    'data'?: { [key: string]: Array<Array<number>>; } | null;
    /**
     * This field is deprecated, please use the \'data\' field instead
     * @type {{ [key: string]: Array<Array<number>>; }}
     * @memberof UpdateCostMatricesProperty5
     * @deprecated
     */
    'cost_matrix'?: { [key: string]: Array<Array<number>>; } | null;
}

