/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsageInfo
 */
export interface UsageInfo {
    /**
     * Number of tokens in the prompt.
     * @type {number}
     * @memberof UsageInfo
     */
    'prompt_tokens'?: number;
    /**
     * Total number of tokens used in the request (prompt + completion).
     * @type {number}
     * @memberof UsageInfo
     */
    'total_tokens'?: number;
    /**
     * Number of tokens in the generated completion.
     * @type {number}
     * @memberof UsageInfo
     */
    'completion_tokens'?: number | null;
}

