/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UserImageContent
 */
export interface UserImageContent {
    /**
     * The type of the content part.
     * @type {any}
     * @memberof UserImageContent
     */
    'type': any;
    /**
     * Base64 encoded image data in form of `data:image/{format};base64,{base64encodedimage}`.          If the size of an image is more than 200KB, it needs to be uploaded to a presigned S3 bucket using NVCF Asset APIs.         Once uploaded you can refer to it using the following format: `data:image/png;asset_id,{asset_id}`.         Accepted formats are `jpg`, `png` and `jpeg`.
     * @type {string}
     * @memberof UserImageContent
     */
    'image_url': string;
}

