/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UserTextContent
 */
export interface UserTextContent {
    /**
     * The type of the content part.
     * @type {any}
     * @memberof UserTextContent
     */
    'type': any;
    /**
     * The text content.
     * @type {string}
     * @memberof UserTextContent
     */
    'text': string;
}

