/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LocationPropertyInner } from './location-property-inner';

/**
 * 
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * 
     * @type {Array<LocationPropertyInner>}
     * @memberof ValidationError
     */
    'loc': Array<LocationPropertyInner>;
    /**
     * The error message.
     * @type {string}
     * @memberof ValidationError
     */
    'msg': string;
    /**
     * Error type
     * @type {string}
     * @memberof ValidationError
     */
    'type': string;
}

