/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface VideoRequest
 */
export interface VideoRequest {
    /**
     * A base64-encoded string of the initial image that will be scaled to 1024x576. Images should be in form of `data:image/{format};base64,{base64encodedimage}` if it\'s smaller than 200KB. Otherwise, it needs to be uploaded to a presigned S3 bucket using NVCF Asset APIs.Once uploaded you can refer to it using the following format: `data:image/png;asset_id,{asset_id}`.Accepted formats are `jpg`, `png` and `jpeg`.
     * @type {string}
     * @memberof VideoRequest
     */
    'image': string;
    /**
     * The seed which governs generation. Omit this option or use 0 for a random seed
     * @type {number}
     * @memberof VideoRequest
     */
    'seed'?: number | null;
    /**
     * How strongly the video sticks to the original image. Use lower values to allow the model more freedom to make changes and higher values to correct motion distortions.
     * @type {number}
     * @memberof VideoRequest
     */
    'cfg_scale'?: number | null;
    /**
     * Controls how much motion to add/remove from the image. Only motion_bucket_id=127 is supported
     * @type {number}
     * @memberof VideoRequest
     */
    'motion_bucket_id'?: number | null;
}

