/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WaypointGraph
 */
export interface WaypointGraph {
    /**
     * dtype: int32, edge >= 0.    Vertices of all the directed edges.
     * @type {Array<number>}
     * @memberof WaypointGraph
     */
    'edges': Array<number>;
    /**
     * dtype: int32, offset >= 0.    Offsets which provide number of edges from the source vertex signified by the index.
     * @type {Array<number>}
     * @memberof WaypointGraph
     */
    'offsets': Array<number>;
    /**
     * dtype: float32, weight >= 0.    Weights of each edges.
     * @type {Array<number>}
     * @memberof WaypointGraph
     */
    'weights'?: Array<number> | null;
}

