/*
Earth-2 Inference Server

API for submitting to the Earth-2 Inference Server.

The version of the OpenAPI document: 0.1.0
Contact: earth2-support@exchange.nvidia.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Window domain, specifies a lat/lon rectangle.  Parameters ---------- lat_min : float     Minimum latitude lon_min : float     Maximum longitude lon_min : float     Minimum longitude east lon_max : float     Maximum longitude east diagnostics : List[Diagnostic]     List of diagnostics to be computed for this domain.
 * @export
 * @interface Window
 */
export interface Window {
    /**
     * 
     * @type {number}
     * @memberof Window
     */
    'lat_max'?: number;
    /**
     * 
     * @type {number}
     * @memberof Window
     */
    'lat_min'?: number;
    /**
     * 
     * @type {number}
     * @memberof Window
     */
    'lon_max'?: number;
    /**
     * 
     * @type {number}
     * @memberof Window
     */
    'lon_min'?: number;
    /**
     * 
     * @type {string}
     * @memberof Window
     */
    'name': string;
    /**
     * 
     * @type {any}
     * @memberof Window
     */
    'type'?: any;
}

